# Generated by Django 2.0.7 on 2018-07-29 00:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
