# Generated by Django 2.0.7 on 2018-07-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64)),
                ('menuItem', models.CharField(max_length=64)),
                ('kindOfPizza', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('topping1', models.CharField(max_length=64)),
                ('topping2', models.CharField(max_length=64)),
                ('topping3', models.CharField(max_length=64)),
            ],
        ),
    ]
