# Generated by Django 2.0.7 on 2018-07-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180728_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('extras', models.CharField(max_length=64)),
                ('extraCheese', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='topping1',
            new_name='toppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping3',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='special',
            field=models.BooleanField(),
        ),
    ]
