# Generated by Django 2.0.7 on 2018-07-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180728_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
