# Generated by Django 2.0.7 on 2018-07-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('extras', models.CharField(max_length=64)),
                ('extraCheese', models.CharField(max_length=64)),
            ],
        ),
    ]
