# Generated by Django 2.0.7 on 2018-07-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='special',
            field=models.CharField(max_length=64),
        ),
    ]
