# Generated by Django 2.0.7 on 2018-07-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_pastatypes_pizzatypes_plattertypes_saladtypes_subtypes_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pastaTypes',
            new_name='pastaType',
        ),
        migrations.RenameModel(
            old_name='subTypes',
            new_name='pizzaType',
        ),
        migrations.RenameModel(
            old_name='saladTypes',
            new_name='platterType',
        ),
        migrations.RenameModel(
            old_name='platterTypes',
            new_name='saladType',
        ),
        migrations.RenameModel(
            old_name='pizzaTypes',
            new_name='subType',
        ),
        migrations.RenameModel(
            old_name='toppings',
            new_name='topping',
        ),
    ]
