# Generated by Django 2.0.7 on 2018-07-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180728_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
    ]
