# Generated by Django 2.0.7 on 2018-07-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_topping_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='platterType',
        ),
    ]
