# Generated by Django 2.0.7 on 2018-07-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzatype',
            name='item',
            field=models.CharField(default='Pizza', max_length=64),
        ),
    ]
