# Generated by Django 2.0.7 on 2018-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_pizzatype_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatype',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
