# Generated by Django 2.0.7 on 2018-07-30 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180729_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzatype',
            name='special',
        ),
    ]
