# Generated by Django 2.0.7 on 2018-07-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20180729_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('item', models.CharField(default='Pizza', max_length=64)),
                ('special', models.BooleanField(default=True)),
                ('size', models.CharField(default='Small', max_length=64)),
                ('toppings', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='menuItem',
        ),
    ]
