# Generated by Django 2.0.7 on 2018-07-30 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20180729_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
